module.exports = {
  extends: ['./tsNext.js'].map(require.resolve),
  rules: {
    '@typescript-eslint/no-unused-vars': 'warn',
    '@typescript-eslint/member-ordering': 'warn',
    'no-async-promise-executor': 'warn',
    'no-restricted-globals': 'warn',
    'no-case-declarations': 'warn',
    'no-script-url': 'warn',
    'no-return-await': 'warn',
    'no-restricted-syntax': 'warn',
    'no-labels': 'warn',
    'no-plusplus': 'warn',
    'no-empty': 'warn',
    'react/no-unused-state': 'warn',
    'react/sort-comp': 'warn',
    'no-useless-escape': 'warn',
    'no-return-assign': 'warn',
    'array-callback-return': 'warn',
    'no-new': 'warn',
    'react/jsx-pascal-case': 'warn',
    'react/no-unused-prop-types': 'warn',
    '@typescript-eslint/no-use-before-define': 'warn',
    'no-lonely-if': 'warn',
    'no-void': 'warn',
    'react/no-did-update-set-state': 'warn',
    'no-empty-pattern': 'warn',
    'no-multi-str': 'warn',
    'no-dupe-keys': 'warn',
    'no-irregular-whitespace': 'warn',
    'no-tabs': 'warn',
    'no-useless-concat': 'warn',
    'prefer-const': 'warn',
  },
}
